---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_tcptraffic
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  English: 0
  File::Basename: 0
  Nagios::Plugin: 0
  Nagios::Plugin::Range: 0
  Nagios::Plugin::Threshold: 0
  Readonly: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.2.5
